version: "4.39"

services:
  postgres:
    image: bitnami/postgresql:17.5.0
    container_name: api-angolan-universities
    environment:
      POSTGRESQL_USERNAME: ${POSTGRESQL_USERNAME}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRESQL_DATABASE: ${POSTGRESQL_DATABASE}
      POSTGRESQL_HOST: ${POSTGRESQL_HOST}
      POSTGRESQL_PORT: ${POSTGRESQL_PORT}
      POSTGRESQL_SCHEMA: ${POSTGRESQL_SCHEMA}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/pg:/data/postgres